export const enumAPItems = {
    progressive_extractor: "Progressive Extractor",
    progressive_cutter: "Progressive  Cutter",
    progressive_rotator: "Progressive Rotator",
    progressive_painter: "Progressive Painter",
    progressive_tunnel: "Progressive Tunnel",
    progressive_balancer: "Progressive Balancer",
    belt: "Belt",
    extractor: "Extractor",
    extractor_chainable: "Chaining Extractor",
    cutter: "Cutter",
    cutter_quad: "Quad Cutter",
    rotator: "Rotator",
    rotator_ccw: "Rotator (CCW)",
    rotator_180: "Rotator (180°)",
    painter: "Painter",
    painter_double: "Double Painter",
    painter_quad: "Quad Painter",
    mixer: "Color Mixer",
    stacker: "Stacker",
    balancer: "Balancer",
    balancer_merger: "Compact Merger",
    balancer_splitter: "Compact Splitter",
    tunnel: "Tunnel",
    tunnel_tier_2: "Tunnel Tier II",
    trash: "Trash",
    reader: "Belt Reader",
    storage: "Storage",
    lever: "Switch",
    filter: "Item Filter",
    display: "Display",
    wires: "Wires",
    constant_signal: "Constant Signal",
    logic_gate: "Logic Gates",
    virtual_processor: "Virtual Processing",
    blueprints: "Blueprints",
    upgrade_small_belt: "Small Belt Upgrade",
    upgrade_small_miner: "Small Miner Upgrade",
    upgrade_small_processors: "Small Processors Upgrade",
    upgrade_small_painting: "Small Painting Upgrade",
    upgrade_big_belt: "Big Belt Upgrade",
    upgrade_big_miner: "Big Miner Upgrade",
    upgrade_big_processors: "Big Processors Upgrade",
    upgrade_big_painting: "Big Painting Upgrade",
    upgrade_gigantic_belt: "Gigantic Belt Upgrade",
    upgrade_gigantic_miner: "Gigantic Miner Upgrade",
    upgrade_gigantic_processors: "Gigantic Processors Upgrade",
    upgrade_gigantic_painting: "Gigantic Painting Upgrade",
    upgrade_rising_belt: "Rising Belt Upgrade",
    upgrade_rising_miner: "Rising Miner Upgrade",
    upgrade_rising_processors: "Rising Processors Upgrade",
    upgrade_rising_painting: "Rising Painting Upgrade",
    bundle_blueprint: "Blueprint Shapes Bundle",
    bundle_level: "Level Shapes Bundle",
    bundle_upgrade: "Upgrade Shapes Bundle",
    trap_drain_inventory: "Inventory Draining Trap",
    trap_drain_shapes_blueprint: "Blueprint Shapes Draining Trap",
    trap_drain_shapes_level: "Level Shapes Draining Trap",
    trap_drain_shapes_upgrade: "Upgrade Shapes Draining Trap",
    trap_building_lock: "Locked Building Trap",
    trap_building_throttle: "Throttled Building Trap",
    trap_building_malfunction: "Malfunctioning Trap",
    trap_upgrade_normal_belt: "Belt Upgrade Trap",
    trap_upgrade_normal_miner: "Miner Upgrade Trap",
    trap_upgrade_normal_processors: "Processors Upgrade Trap",
    trap_upgrade_normal_painting: "Painting Upgrade Trap",
    trap_upgrade_demonic_belt: "Demonic Belt Upgrade Trap",
    trap_upgrade_demonic_miner: "Demonic Miner Upgrade Trap",
    trap_upgrade_demonic_processors: "Demonic Processors Upgrade Trap",
    trap_upgrade_demonic_painting: "Demonic Painting Upgrade Trap",
    upgrade_big_random: "Big Random Upgrade",
    upgrade_small_random: "Small Random Upgrade",
    trap_inflation: "Inflation Trap",
    trap_clear_belts: "Belts Clearing Trap",
};
